[package]
name = "libglutin"
version = "0.2.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
glutin = { git = "https://github.com/syrel/glutin" }
libc = "0.2.65"
boxer = { git = "https://github.com/feenkcom/gtoolkit-boxer" }

[patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit", rev = "9daa0738a9aeb60768d9b7d19f4e3deddd55958b" }

[target.'cfg(windows)'.patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit", rev = "627a127f1b96608649eee5ac474bf762daffbc3a" }

[lib]
name = "Glutin"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
opt-level = 3