[package]
name = "libglutin"
version = "0.2.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
glutin = { git = "https://github.com/syrel/glutin", rev ="7d0df6ec3563173456fcc214e1a5f399fdfd7225" }
libc = "0.2.80"
boxer = { git = "https://github.com/feenkcom/gtoolkit-boxer", rev = "8ffd345b6aabda55c5ab1b4914f6f3e5f92918d4" }
log = "0.4"
env_logger = "0.7"

[patch.crates-io]
winit = { git = "https://github.com/syrel/winit", rev = "9a5827e47b60a038a097c2746ea8b325b0b5ac98" }

[lib]
name = "Glutin"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
opt-level = 3