[package]
name = "libglutin"
version = "0.1.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
glutin = { git = "https://github.com/rust-windowing/glutin" }
gleam = "0.6.17"
libc = "0.2.54"
winit = { git = "https://github.com/rust-windowing/winit.git", branch = "eventloop-2.0"}

[lib]
name = "Glutin"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3