[package]
name = "libglutin"
version = "0.2.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
glutin = "0.22.0-alpha3"
gleam = "0.8.0"
libc = "0.2.65"
boxer = { git = "https://github.com/feenkcom/libboxer" }

[patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit.git", rev = "429bbfade0ee68f7d3f8ba89498984b72b805f13" }

[lib]
name = "Glutin"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3