[package]
name = "libglutin"
version = "0.2.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
glutin = "0.22.0-alpha1"
gleam = "0.6.18"
libc = "0.2.60"

[lib]
name = "Glutin"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3