[package]
name = "libglutin"
version = "0.1.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
glutin = "0.20.0"
gleam = "0.6.14"
libc = "0.2"

[lib]
name = "Glutin"
crate-type = ["cdylib"]