[workspace]

members = [
    "library",
    "shared-library-builder/library",
    "shared-library-builder/builder",
]

exclude = [ "target" ]

[patch.crates-io]
winit = { git = "https://github.com/syrel/winit", rev = "5049af04eb85456d0762a0be51d44682e1c33343" }

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
opt-level = 3