[package]
name = "libglutin"
version = "0.2.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
glutin = "0.22.0-alpha3"
gleam = "0.6.19"
libc = "0.2.62"
boxer = { git = "https://github.com/syrel/rust-boxer" }

[patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit.git" }

[lib]
name = "Glutin"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3