[package]
name = "libglutin"
version = "0.2.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
glutin = { git = "https://github.com/syrel/glutin", rev ="0b1971f880f68ee3c2dd83e777b6f20be980c3b4" }
libc = "0.2.65"
boxer = { git = "https://github.com/feenkcom/gtoolkit-boxer" }

[patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit", rev = "1f24a09570d3bf0a39af836c3a7c212a0b65ff70" }

[lib]
name = "Glutin"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
opt-level = 3