[package]
name = "libglutin"
version = "0.1.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
glutin = "0.21.0"
gleam = "0.6.16"
libc = "0.2"

[lib]
name = "Glutin"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3