[package]
name = "libglutin"
version = "1.0.0"
authors = ["feenk gmbh. <contact@feenk.com>"]
edition = "2021"

[dependencies]
glutin = { git = "https://github.com/syrel/glutin", rev ="6ac2c1c008d87f34bbe810f7f0e348c88b5d67c7" }
raw-window-handle = "0.4"
log = "0.4"
env_logger = "0.10"
# value-box support
value-box = "2.2"
geometry-box = "1.0"
string-box = "1.1"
value-box-ffi = { version = "1.0", features = [ "geometry-box", "string-box"] }

[lib]
name = "Glutin"
crate-type = ["cdylib"]
