[package]
name = "libglutin"
version = "0.3.0"
authors = ["feenk gmbh. <contact@feenk.com>"]
edition = "2021"

[dependencies]
glutin = { git = "https://github.com/syrel/glutin", rev ="6ac2c1c008d87f34bbe810f7f0e348c88b5d67c7" }
raw-window-handle = "0.3"
boxer = { git = "https://github.com/feenkcom/gtoolkit-boxer", rev = "8ffd345b6aabda55c5ab1b4914f6f3e5f92918d4" }
log = "0.4.16"
env_logger = "0.9.0"

[lib]
name = "Glutin"
crate-type = ["cdylib"]
